version: '2'
services:
  haryali-app:
    image: haryali
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://haryali-postgresql:5432/haryali
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://haryali-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://haryali-elasticsearch:9200
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - 8080:8080
  haryali-postgresql:
    extends:
      file: postgresql.yml
      service: haryali-postgresql
  haryali-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: haryali-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
